services:
  deepstream:
    build:
      context: .
      args:
        - BASE_IMAGE=nvcr.io/nvidia/deepstream:6.0-samples
    cap_add: ["SYSLOG"]
    entrypoint:
      [
        "jupyter",
        "notebook",
        "--ip=0.0.0.0",
        "--no-browser",
        "--allow-root",
        "--port=8888",
        "--notebook-dir=/opt/nvidia/deepstream/deepstream-6.0/samples",
        "--NotebookApp.token=''",
        "--NotebookApp.password=''",
        "--NotebookApp.allow_origin='*'",
        "--NotebookApp.base_url=/",
      ]
    hostname: deepstream
    image: deepstream:6.0-jupyter
    network_mode: "host"
    platform: linux/amd64
    ports:
      - "8888:8888"
    runtime: nvidia
    working_dir: /opt/nvidia/deepstream/deepstream-6.0/samples

  deepstream-l4t:
    build:
      context: .
      args:
        - BASE_IMAGE=nvcr.io/nvidia/deepstream-l4t:6.0-samples
    cap_add: ["SYSLOG"]
    entrypoint:
      [
        "jupyter",
        "notebook",
        "--ip=0.0.0.0",
        "--no-browser",
        "--allow-root",
        "--port=8888",
        "--notebook-dir=/opt/nvidia/deepstream/deepstream-6.0/samples",
        "--NotebookApp.token=''",
        "--NotebookApp.password=''",
        "--NotebookApp.allow_origin='*'",
        "--NotebookApp.base_url=/",
      ]
    environment:
      - DISPLAY=:0
    hostname: deepstream
    image: deepstream:6.0-jupyter-l4t
    network_mode: "host"
    platform: linux/arm64
    runtime: nvidia
    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: /tmp/argus_socket
        target: /tmp/argus_socket
    working_dir: /opt/nvidia/deepstream/deepstream-6.0/samples
