services:
  deepstream-l4t:
    build:
      context: .
    cap_add: ["SYSLOG"]
    entrypoint:
      [
        "deepstream-app",
        "-c",
        "samples/configs/deepstream-app/source1_csi_dec_infer_resnet_int8.txt",
      ]
    environment:
      - DISPLAY=:0
    hostname: deepstream
    image: deepstream:6.0-jupyter-l4t
    network_mode: "host"
    platform: linux/arm64
    runtime: nvidia
    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: /tmp/argus_socket
        target: /tmp/argus_socket
    working_dir: /opt/nvidia/deepstream/deepstream-6.0
