version: "3"
services:
  deepstream:
    build:
      context: .
      args:
        - BASE_IMAGE=nvcr.io/nvidia/deepstream:6.0-samples
    environment:
      - DISPLAY=$DISPLAY
    entrypoint:
      [
        "jupyter",
        "lab",
        "--ip=0.0.0.0",
        "--no-browser",
        "--allow-root",
        "--port=8888",
        "--ServerApp.token=''",
        "--ServerApp.password=''",
        "--ServerApp.allow_origin='*'",
        "--ServerApp.base_url=/",
      ]
    hostname: deepstream
    image: deepstream:6.0-jupyter
    platform: linux/amd64
    ports:
      - "8888:8888"
    runtime: nvidia
    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: ./notebooks/DeepStreamSamples.ipynb
        target: /opt/nvidia/deepstream/deepstream/samples/DeepStreamSamples.ipynb
    working_dir: /opt/nvidia/deepstream/deepstream-6.0

  deepstream-l4t:
    build:
      context: .
      args:
        - BASE_IMAGE=nvcr.io/nvidia/deepstream-l4t:6.0-samples
    environment:
      - DISPLAY=$DISPLAY
    entrypoint:
      [
        "jupyter",
        "lab",
        "--ip=0.0.0.0",
        "--no-browser",
        "--allow-root",
        "--port=8888",
        "--ServerApp.token=''",
        "--ServerApp.password=''",
        "--ServerApp.allow_origin='*'",
        "--ServerApp.base_url=/",
      ]
    hostname: deepstream
    image: deepstream:6.0-jupyter-l4t
    platform: linux/arm64
    ports:
      - "8888:8888"
    runtime: nvidia
    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: ./notebooks/DeepStreamSamples.ipynb
        target: /opt/nvidia/deepstream/deepstream-6.0-6.0/samples/DeepStreamSamples.ipynb
    working_dir: /opt/nvidia/deepstream/deepstream-6.0-6.0
